[package]
name = "pi-monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", features = ["ws"] }
axum-extra = { version = "0.12.6", features = ["typed-header"] }
futures = "0.3.34"
futures-util = "0.3.34"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sysinfo = "0.39.6"
tokio = { version = "1.53.1", features = ["full"] }
tower-http = { version = "0.7.1", features = ["fs"] }
